version: "3.8"

services:
  postgres:
    restart: always
    image: "postgres:latest"
    environment:
      - POSTGRES_DB=reddit_clone
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: "redis:latest"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    command:
      [
        "bash",
        "-c",
        "go build -v -o main ./cmd/app && ./main --storage ${STORAGE}",
      ]

volumes:
  postgres_data:
