// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthPayload struct {
	Token string `json:"token"`
}

type LoginUser struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type NewComment struct {
	PostID          string  `json:"postId"`
	ParentCommentID *string `json:"parentCommentId,omitempty"`
	UserID          string  `json:"userId"`
	Content         string  `json:"content"`
}

type NewPost struct {
	UserID  string `json:"userId"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

type NewUser struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type PostCommentState struct {
	UserID          string `json:"userId"`
	PostID          string `json:"postId"`
	CommentsEnabled bool   `json:"commentsEnabled"`
}

type Query struct {
}

type Subscription struct {
}
